### ISSUE TITLE
Figure out where FAST Events that do not have a equivalent VIAF should go?

### ISSUE THREAD

**Issue by thisismattmiller** [nypl-registry/ingest-fast#1]
http://fast.oclc.org/searchfast/?&limit=keywords&facet=all&query=Sino-Japanese%20War%20(1937-1945)&sort=usage+desc&start=0#&single=fst01431391&fullview=simple&sep=click

Right now anytime there is an FAST event with no match in VIAF it will be added as an term.

That may not be the best as it fractures FAST Events between Agents and Terms.

**Comment by saverkamp** [comment]
Should all events be Agents, though? Conferences and meetings are Agents when they're considered as contributors to a resource, such as conference proceedings, but in this case the event is not contributing to the creation of a resource.

**Comment by thisismattmiller** [comment]
True, but FAST does not distinguish between conference/meeting events and other events, they are just all events. But you are saying it is probably fine if an event that has an existing VIAF we just make it an Agent and if not then it belongs in Terms as an Event type? I agree, hopefully FAST converted all possible Event like LCSH topical heading to Events. 

But without reconciliation help from WC/Classify the Terms process would not be able to convert random preconfigured subject headings into FAST Events. For example http://catalog.nypl.org/record=b14331619 has `Triangle Shirtwaist Company -- Fire, 1911.` but WC tells us it is http://experimental.worldcat.org/fast/1355168/ without WC it would just be two topical terms. But I think that is unavoidable at this stage.

**Comment by thisismattmiller** [comment]
I think the same question applies to Geographical FAST terms, since they too can exist in VIAF. Something to discuss more.

**Comment by saverkamp** [comment]
Resolved -- now events that match in VIAF go to Agents. Those that do not match in VIAF go to Terms as FAST events.
